version: '3.8'

services:
  alb-simulator:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-dns-failure.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache-dns-failure
    restart: unless-stopped

  apache-dns-failure:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./apache-dns-fail.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - backend-app
    restart: unless-stopped

  backend-app:
    image: python:3.9-slim
    volumes:
      - ../../common/backend-app.py:/app/app.py
    working_dir: /app
    command: sh -c "pip install flask && python app.py"
    ports:
      - "5000:5000"
    environment:
      - SERVER_NAME=dns-failure-backend
    restart: unless-stopped
